;; Key bindings
(global-set-key [(ctrl x) (i)] 'windmove-up)
(global-set-key [(ctrl x) (m)] 'windmove-down)
(global-set-key [(ctrl x) (j)] 'windmove-left)
(global-set-key [(ctrl x) (l)] 'windmove-right)
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-w" 'backward-kill-word) 
(global-set-key "\C-x\C-k" 'kill-region)
(global-set-key "\C-x\C-j" 'copy-region-as-kill)
(global-set-key "\C-x\C-n" 'compile)
(global-set-key "\C-cn" 'compilation-mode)
(global-set-key (kbd "<mouse-5>") 'up-slightly)
(global-set-key (kbd "<mouse-4>") 'down-slightly)
(global-set-key "\C-l" 'line-to-top-of-window)
(global-set-key [f9] 'match-paren)
(global-set-key [f10] 'start-kbd-macro)
(global-set-key [f11] 'end-kbd-macro)
(global-set-key [f12] 'call-last-kbd-macro)
